# NumPy exercises

We are going to practice NumPy skills and basic syntax.

We put here also some examples that were not in the tutorial on purpose. Try to use google and offial NumPy documentation to solve these exercises.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [3]:
import numpy as np

#### 2. Create a null vector of size 10 (★☆☆)

In [5]:
x = np.zeros(10)

In [6]:
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 3.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [7]:
x[4]=1

In [8]:
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 4.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [13]:
y = np.arange(10,50)

In [10]:
y

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 5.  Reverse a vector (first element becomes last) (★☆☆)

In [14]:
y = y[::-1]

In [15]:
y

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 6.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [16]:
A = np.matrix([[1,2,3],[4,5,6],[7,8,9]])

In [17]:
A

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [19]:
B = np.arange(0,9).reshape(3,3)

In [20]:
B

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 7. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [21]:
b = np.array([1,2,0,0,4,0])

In [23]:
for i in range(len(b)):
    if b[i] == 0:
        print(i)

2
3
5


#### 8. Create a 3x3x3 array with random values (★☆☆)

In [24]:
C = np.random.random((3,3,3))

In [25]:
C

array([[[0.66678237, 0.06077875, 0.34613232],
        [0.9563832 , 0.0538075 , 0.91126221],
        [0.4284114 , 0.01360703, 0.35355997]],

       [[0.29566851, 0.76249342, 0.40237388],
        [0.58302119, 0.96731119, 0.68410153],
        [0.81670732, 0.86980149, 0.91681802]],

       [[0.76985218, 0.13797342, 0.62707955],
        [0.60769228, 0.8731882 , 0.55792569],
        [0.24289149, 0.84996495, 0.22031812]]])

#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [26]:
B = np.random.random((10,10))
B

array([[0.42991834, 0.6828825 , 0.28828196, 0.57232953, 0.56056648,
        0.79327931, 0.30420621, 0.25402182, 0.72549371, 0.62596569],
       [0.49301054, 0.52109322, 0.91013954, 0.76781328, 0.02436974,
        0.81821629, 0.92735588, 0.12599195, 0.5224052 , 0.13958698],
       [0.16373227, 0.79682545, 0.62550536, 0.3619837 , 0.71113097,
        0.36989826, 0.65565578, 0.69005729, 0.23149432, 0.20617604],
       [0.21073892, 0.90124268, 0.59019788, 0.15169085, 0.69512872,
        0.5708231 , 0.96923903, 0.73952299, 0.37293757, 0.79836244],
       [0.91064385, 0.18664963, 0.72634994, 0.2719443 , 0.83572853,
        0.38956407, 0.90308218, 0.58412503, 0.28865866, 0.62649596],
       [0.64360531, 0.48130931, 0.98737664, 0.54009365, 0.29712312,
        0.74099476, 0.85257721, 0.0281332 , 0.86427281, 0.09886251],
       [0.2824455 , 0.89479241, 0.97770271, 0.36626751, 0.82611836,
        0.46532692, 0.81547598, 0.50648621, 0.75918476, 0.38088145],
       [0.64407003, 0.04915323, 0.4189213

In [28]:
Bmin, Bmax = B.min(), B.max()

In [29]:
Bmin, Bmax

(0.02436974200524722, 0.9873766444324035)

#### 10. Create a random vector of size 30 and find the mean value (★☆☆)

In [36]:
C = np.random.random(30)

In [38]:
C_mean = C.mean()

In [39]:
C_mean

0.45950283618368726

#### 11. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [40]:
x= np.ones((5,5))
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [41]:
x[1:-1,1:-1] = 0
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 12. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [44]:
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)

In [45]:
x

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### 13. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [46]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

#### 14. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [49]:
V = np.diag(np.arange(1,5), k=-1)
V

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [51]:
#Create a 5x5 matrix


#### 15. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [52]:
r = np.random.random((6,7,8))

In [63]:
np.unravel_index(100, (6,7,8))

(1, 5, 4)

#### 16. Normalize a 5x5 random matrix (★☆☆)

In [68]:
x = np.random.random((5,5))

In [69]:
x

array([[0.29874164, 0.54374811, 0.68976699, 0.1523137 , 0.62277924],
       [0.56221502, 0.36314137, 0.14262163, 0.80330203, 0.44358727],
       [0.30514263, 0.60457621, 0.94992002, 0.05662014, 0.45911861],
       [0.77769732, 0.96155223, 0.0365002 , 0.0836358 , 0.32508374],
       [0.88742352, 0.85843472, 0.0392818 , 0.46280282, 0.39316663]])

#### 17. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [71]:
x = np.arange(1,100,2)

In [75]:
x

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [77]:
x[3:8] = -1 * x[3:8]

In [78]:
x

array([  1,   3,   5,  -7,  -9, -11, -13, -15,  17,  19,  21,  23,  25,
        27,  29,  31,  33,  35,  37,  39,  41,  43,  45,  47,  49,  51,
        53,  55,  57,  59,  61,  63,  65,  67,  69,  71,  73,  75,  77,
        79,  81,  83,  85,  87,  89,  91,  93,  95,  97,  99])

#### 18. How to round away from zero a float array ? (★☆☆)

In [97]:
x = np.array([-20.7, -21.4, -22.5, -23.2,  10.3,  11.8,  12.9,  13.3])

In [99]:
def round_away(x):
    a=np.abs(x)
    b=np.ceil(a)
    return np.sign(x)*b 

In [100]:
round_away(x)

array([-21., -22., -23., -24.,  11.,  12.,  13.,  14.])

#### 19. Find common values between two arrays? (★☆☆)

In [102]:
x = np.arange(1,16,1)
y = np.arange(5,20,1)

In [104]:
def common(x,y):
    return np.intersect1d(x,y)

In [105]:
common(x,y)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

#### 20. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [106]:
np.sqrt(-1) == np.emath.sqrt(-1)

/var/folders/sy/61n20bpj6f9dzqcywtfdt3z00000gn/T/ipykernel_24312/244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 21. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [110]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=int,count=-1)
print(Z)

[0 1 2 3 4 5 6 7 8 9]


In [111]:
np.fromiter?

Docstring:
fromiter(iter, dtype, count=-1, *, like=None)

Create a new 1-dimensional array from an iterable object.

Parameters
----------
iter : iterable object
    An iterable object providing data for the array.
dtype : data-type
    The data-type of the returned array.

    .. versionchanged:: 1.23
        Object and subarray dtypes are now supported (note that the final
        result is not 1-D for a subarray dtype).

count : int, optional
    The number of items to read from *iterable*.  The default is -1,
    which means all data is read.
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array object
    compatible with that passed in via this argument.

    .. versionadded:: 1.20.0

Returns
-------
out : ndarray
    The output array.

Notes
-----


#### 22. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [114]:
P = np.linspace(0,1,12,endpoint=True)

In [115]:
P

array([0.        , 0.09090909, 0.18181818, 0.27272727, 0.36363636,
       0.45454545, 0.54545455, 0.63636364, 0.72727273, 0.81818182,
       0.90909091, 1.        ])

#### 23. Create a random vector of size 10 and sort it (★★☆)

In [119]:
x = np.sort(np.random.random(10))
x

array([0.05416424, 0.22730789, 0.30565448, 0.34616944, 0.42421704,
       0.4767592 , 0.58223084, 0.59591453, 0.60790883, 0.64987167])

#### 24. Consider two random arrays A and B, check if they are equal (★★☆)

In [120]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

In [122]:
equal = np.array_equal(A,B)
print(equal)

True


#### 25. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [125]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [129]:
x[x.max()] = 0

In [130]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 0])

#### 26. Find the closest value to random element in a vector? (★★☆)

In [132]:
x = np.random.random(20)
x

array([0.27700327, 0.49279956, 0.61109906, 0.28926842, 0.18604962,
       0.2147306 , 0.024073  , 0.72205323, 0.81483462, 0.05961707,
       0.43183177, 0.09393339, 0.95763425, 0.83140546, 0.81289208,
       0.54401447, 0.68499623, 0.12711941, 0.99719717, 0.819887  ])

In [140]:
def find_closest(x, y):
    index = (np.abs(x-y)).argmin()
    return x[index]

In [141]:
find_closest(x, 9)

0.9971971685370838

#### 27. Convert a float (32 bits) array into an integer (32 bits) in place?

In [139]:
np.argmin?

Signature: np.argmin(a, axis=None, out=None, *, keepdims=<no value>)
Docstring:
Returns the indices of the minimum values along an axis.

Parameters
----------
a : array_like
    Input array.
axis : int, optional
    By default, the index is into the flattened array, otherwise
    along the specified axis.
out : array, optional
    If provided, the result will be inserted into this array. It should
    be of the appropriate shape and dtype.
keepdims : bool, optional
    If this is set to True, the axes which are reduced are left
    in the result as dimensions with size one. With this option,
    the result will broadcast correctly against the array.

    .. versionadded:: 1.22.0

Returns
-------
index_array : ndarray of ints
    Array of indices into the array. It has the same shape as `a.shape`
    with the dimension along `axis` removed. If `keepdims` is set to True,
    then the size of `axis` will be 1 with the resulting array having same
    shape as `a.shape`.

See Also
--------

#### 28. Sort an array by the nth column? (★★☆)

In [142]:
Z = np.random.randint(0,10,(3,3))
Z

array([[9, 0, 1],
       [7, 3, 1],
       [7, 3, 3]])

#### 29. Find if a given 2D array has null (empty) columns? (★★☆)

In [144]:
X = np.random.randint(0,10,(3,5))
X

array([[3, 9, 1, 0, 8],
       [3, 5, 6, 5, 9],
       [5, 9, 6, 5, 8]])

In [145]:
~Z.any(axis=0).any()

False

In [146]:
np.any?

Signature: np.any(a, axis=None, out=None, keepdims=<no value>, *, where=<no value>)
Docstring:
Test whether any array element along a given axis evaluates to True.

Returns single boolean if `axis` is ``None``

Parameters
----------
a : array_like
    Input array or object that can be converted to an array.
axis : None or int or tuple of ints, optional
    Axis or axes along which a logical OR reduction is performed.
    The default (``axis=None``) is to perform a logical OR over all
    the dimensions of the input array. `axis` may be negative, in
    which case it counts from the last to the first axis.

    .. versionadded:: 1.7.0

    If this is a tuple of ints, a reduction is performed on multiple
    axes, instead of a single axis or all the axes as before.
out : ndarray, optional
    Alternate output array in which to place the result.  It must have
    the same shape as the expected output and its type is preserved
    (e.g., if it is of type float, then it will remain so, retu

#### 30. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [156]:
v = np.array([1,2,3,4,5])
V0 = np.zeros((len(v)+1)*3)
v, V0


(array([1, 2, 3, 4, 5]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.]))

In [158]:
V0[::4] = v
V0

array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.,
       0.])

#### 31. Swap two rows of an array? (★★★)

In [159]:
v

array([1, 2, 3, 4, 5])

#### 32. How to negate a boolean value inside an array? (★★★)

#### 33. Find the most frequent value in an array?

#### 34. Get the n largest values of an array (★★★)

#### 35. Extract unique rows from a two dimensional array? (★★★)